# Customized rubocop rules
# Defaults can be found at https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
Layout/LineLength:
  Max: 100

Style/SingleLineBlockParams:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
